# This file was generated by GoReleaser. DO NOT EDIT.
cask "kraai" do
  version "0.6.6"

  on_macos do
    on_arm do
      sha256 "e85d4cea7c1c0fbcedab77201766810babd8bf1328eefc3cb80dcc5b1ed5e2f1"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7f985118918fd6c39636412a590a9c1c0c1d0aea110830644ec07bbec7a7a22"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbf6a785c142d400c603456e8ef46b78e0c10a8cc2d2ed6fdfbc2cfc3ce204a2"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b29aa04601b524a9fbe4ab6b43fa8edde0ace586e02b7c556ee919b2c1a067d"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kraai"
  desc "Declare environments as manifests and apply them with one command."
  homepage "https://github.com/evatt-labs/kraai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kraai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kraai"]
    end
  end

  # No zap stanza required
end
