# This file was generated by GoReleaser. DO NOT EDIT.
cask "kraai" do
  version "0.6.16"

  on_macos do
    on_arm do
      sha256 "b450dc2e53da5aa9ab83aa5f855d1b3d02c10cad077aefa36852cb4a8f72124a"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc9725f1c8f50b0c5589f9682784a7080745a4a18b1e295199026c88c7e557a5"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b04914962bfbb07d44395b1ba7a1a63628256187d3d00b8fcc3810d8f105776f"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "52621deb51f3997253883583432faa6ec77dd5cf25a026cd718c0ebaf5fdccc4"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kraai"
  desc "Declare environments as manifests and apply them with one command."
  homepage "https://github.com/evatt-labs/kraai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kraai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kraai"]
    end
  end

  # No zap stanza required
end
