# This file was generated by GoReleaser. DO NOT EDIT.
cask "kraai" do
  version "0.6.8"

  on_macos do
    on_arm do
      sha256 "9139c927c0a4f297c4d7ddb8252ae4dbb59fbad41b885a08ae0764932c6e424b"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b62ee703be0be6ee1c87fbecb9ea69f71bc70099135853465324c640301663e"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "34c4e4e191fcc26ea417459575f66ee96ea64cc9f772e4a35664cf45ef5dee46"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2775781fd7d4fd867192be7d42419cab727dec6ec95d1e3a1c1fd99078ce63f"
      url "https://github.com/evatt-labs/kraai/releases/download/v#{version}/kraai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kraai"
  desc "Declare environments as manifests and apply them with one command."
  homepage "https://github.com/evatt-labs/kraai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kraai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kraai"]
    end
  end

  # No zap stanza required
end
